language: php

php:
  - 7.2

#env:
#  - TYPO3_VERSON="9.5"

sudo: false

notifications:
  email: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  #- composer require typo3/minimal ${TYPO3_VERSON} --update-with-dependencies
  #- composer require nimut/testing-framework
  - composer require squizlabs/php_codesniffer
  - composer require --dev helmich/typo3-typoscript-lint

script:
  - .Build/bin/phpcs --standard=PSR2 --extensions=php *
  - .Build/bin/typoscript-lint -c tslint.yaml
