<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_statcounter"
 *
 * Auto generated by Extension Builder 2017-08-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN] StatCounter – Free Real Time Visitor Stats',
    'description' => 'StatCounter TYPO3 Extension brings you all the powerful StatCounter features to your TYPO3 site',
    'category' => 'plugin',
    'author' => 'Sanjay Chuahan [NITSAN Technologies]',
    'author_email' => 'sanjay@nitsan.in',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.0.0-9.3.3',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
