# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2017
  project: [NITSAN] StatCounter – Free Real Time Visitor Stat 
  version: 1.2
  release: 1.0.2
  latex_documents:
  - - Index
    - ns_statcounter.tex
    - [NITSAN] StatCounter – Free Real Time Visitor Stat 
    - Sanjay Chuahan [NITSAN Technologies]
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
